apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ws-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: demo-ws-app
  template:
    metadata:
      labels:
        app: demo-ws-app
    spec:
      containers:
        - name: demo-ws-app
          image: docker.io/kbhaskar2021/demo-ws-app:v1.0.5 # {"$imagepolicy": "flux-system:demo-ws-app"}
          command:
            - python
            - -m
            - http.server
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: demo-ws-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: demo-ws-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30010
